version: '3.8'
volumes:
  mysql-data:
services:
  mysql:
    image: mysql:5.7.33
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
