version: "3.8"
volumes:
  mysql-data:
services:
  app:
    build:
      context: .
      target: dev
    depends_on:
      - mysql
    volumes:
      - .:/go/src/github.com/jbielick/dumpctl
  mysql:
    image: mysql:5.7.36
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
